name: Self-hosted Runner Test

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted
    steps: 
      - name: Check runner info
        run: uname -a


      - name: print working directory
        run: pwd

      - name: list files
        run: ls -lah

      - name: bye message
        run: echo "Bye Bye"
