name: Hprofile-actions
on: workflow_dispatch
jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2

      - name: maven test 
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle   
    
